### ISSUE TITLE
Swap cmd.exec for go-git

### ISSUE THREAD

**Issue by Maijin** [radareorg/r2pm#10]
See https://stackoverflow.com/questions/45342640/golang-git-pulling-a-repo/45342748#45342748

**Comment by qbarrand** [comment]
Why should we do this? `go get` [just runs a plain `exec.Cmd.Run()`](https://github.com/golang/tools/blob/b346f7fd45de50e7e5dd5d24a7a009c3c8d8ec61/go/vcs/vcs.go#L215) - since we are doing fairly simple stuff, maybe we can avoid a dependency here.

**Comment by Maijin** [comment]
Mokay, it looked cleaner but if you think that's better to just do bunch of cmd.run no problem.
