### ISSUE TITLE
Add Appveyor

### ISSUE THREAD

**Issue by Maijin** [radareorg/r2pm#12]
Add Appveyor for Windows binaries for r2pm.

**Comment by xarkes** [comment]
You want to build *all* the plugins on it?

**Comment by Maijin** [comment]
No just r2pm

**Comment by xarkes** [comment]
Ah okay.

**Comment by qbarrand** [comment]
Alternatively, we could use `windows` builds on Travis. The library compiles correctly there, but the linker is unable to find `-lr2pm`, so `r2pm_c` cannot be built.

**Comment by XVilka** [comment]
Use Appveyor please, we have a paid support here and 3 parallel builds.
Azure Pipelines is a good candidate too.

**Comment by Maijin** [comment]
@XVilka can you enable it for this repo and add the badge?

**Comment by XVilka** [comment]
https://ci.appveyor.com/project/radare/r2pm
But I don't have an access for the Settings of this project, so can't setup hooks.

**Comment by Maijin** [comment]
Who does you know?

**Comment by XVilka** [comment]
@radare  or @xarkes

**Comment by XVilka** [comment]
@xarkes @radare ping

**Comment by xarkes** [comment]
Yeah sorry I will take care of this in the day or tomorrow at most.

**Comment by XVilka** [comment]
Done.

**Comment by xarkes** [comment]
Fix it and it will be good :-)
