### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by XVilka** [radareorg/r2pm#38]
See:
- https://dependabot.com/go
- https://dependabot.com/docs/config-file/

It checks the dependencies automatically and sends PRs to the repo. Go language is supported.

**Comment by qbarrand** [comment]
Waiting for @radareorg to approve the installation request.

**Comment by radare** [comment]
Done

**Comment by qbarrand** [comment]
Done; no dependabot badge. Thanks for suggesting @XVilka.
