### ISSUE TITLE
I use window 10, and how can I install r2pm for now?

### ISSUE THREAD

**Issue by pharazone** [radareorg/r2pm#5]
I use window 10, and how can I install r2pm for now?

**Comment by radare** [comment]
You cant. r2pm is a shellscript and requires a unix system to work. Also a working compiler, git, wget and many other things that are not available on windows

**Comment by xarkes** [comment]
A new version (cross platform) of r2pm is being developed, so you will have to wait for it.

**Comment by xarkes** [comment]
This repository is the new r2pm which will be cross platform, but you for now it is still work in progress.

**Comment by radare** [comment]
We also plan to distribute precompiled packages. Mainly for windows users, because thats not an issue for android, linux, mac or any other unix system

**Comment by Anutrix** [comment]
May be overkill but installing Radare2 on Windows Subsystem for Linux in might or not be what you are looking for.

**Comment by XVilka** [comment]
@pharazone please try now

**Comment by XVilka** [comment]
Closing because no response, and r2pm supports Windows now.
