### ISSUE TITLE
missing "db.json"

### ISSUE THREAD

**Issue by cxwithyxy** [radareorg/r2pm#6]
I run : 
```
go run r2pm.go -s r2frida
```
it return : 
```
Could not read database file C:\Users\cx\AppData\Roaming/db.json. Did you initialize r2pm? 
```
so, where is the **db.json** ?

**Comment by Maijin** [comment]
did you `r2pm init` ?

**Comment by cxwithyxy** [comment]
I run that, but nothing return

```
go run r2pm.go init
```
actually **r2pm.go** is diff from **r2pm**

 
```
go run r2pm.go -init
```

that works.

but I still can't install r2frida

```
go run r2pm.go -s r2frida
```

it return :

```
List of available packages: (filter: r2frida)
No packages found.
```

**Comment by xarkes** [comment]
As said in my previous message, r2pm.go is a Work In Progress.
What you need to use to install *r2frida* is **r2pm** not ~~r2pm.go~~.
